### ISSUE TITLE
Inaccuracy between real and posted tallies

### ISSUE THREAD

**Issue by s-clerc** [Levelent/PlusBot#1]
# Problem
For the [message](https://discordapp.com/channels/617808182323970058/617810355829211224/694296575379374090), plus board states it is at +7, when in actuality it is at +25.

([Also for](https://discordapp.com/channels/617808182323970058/681347708564406278/694273966688174101))

# Steps to reproduce:
0. Go to [message](https://discordapp.com/channels/617808182323970058/617810355829211224/694296575379374090) and tally +1s.
1. Go to [plusboard tally](https://discordapp.com/channels/617808182323970058/681347708564406278/694298341042815064) and see tally of +1s.
2. Compare tally.

## Expected result

Tallies should be equal.

**Comment by Levelent** [comment]
Not relevant to the actual project, unfortunately - this is an issue with a different bot which I don't develop.
